### Get All Categories
GET {{host}}/public/categories

### Get A Category
@categoryId = 1
GET {{host}}/public/categories/{{categoryId}}

### Add A Category
POST {{host}}/admin/categories
Content-Type: application/json

{
  "categoryName": "Toys and Games"
}

### Update A Category
@updateCategoryId = 1
PUT {{host}}/admin/categories/{{updateCategoryId}}
Content-Type: application/json

{
  "categoryName": "Leisure, Entertainment and Recreation"
}

### Delete A Category
@deleteCategoryId = 1
DELETE {{host}}/admin/categories/{{deleteCategoryId}}

##************************************ Product ************************************
##********************************************************************************

### Add A Product
POST {{host}}/admin/1/products
Content-Type: application/json

{
  "productName": "Legal Blocks",
  "description": "Conformable and easy to wear",
  "quantity": 10,
  "price": 1000.00,
  "discount": 15.00
}


### Get All Products
GET {{host}}/public/products


### Get All Products By Category
GET {{host}}/public/2/products

### Get All Products By Keyword
GET {{host}}/public/products/keyword/legal

### Update a Products
PUT {{host}}/admin/products/1
Content-Type: application/json

{
  "productName": "Custom Legal Blocks",
  "description": "Creative legal pieces the boot innovation in kids",
  "quantity": 45
}