### Get All Categories
GET {{host}}/public/categories

### Get A Category
@categoryId = 3
GET {{host}}/public/categories/{{categoryId}}

### Add A Category
POST {{host}}/admin/categories
Content-Type: application/json

{
  "categoryName": "Entertainment and Receation"
}

### Update A Category
@updateCategoryId = 3
PUT {{host}}/admin/categories/{{updateCategoryId}}
Content-Type: application/json

{
  "categoryName": "Leisure, Entertainment and Recreation"
}

### Delete A Category
@deleteCategoryId = 3
DELETE {{host}}/admin/categories/{{deleteCategoryId}}
